BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXFFFFFFFFFFFFXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Partner Dashboard') XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXX
    XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX gettext(u'Welcome') X XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Partner Dashboard') XXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Memorials') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Pending Tributes') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Approved Tributes') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Create Memorial') XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Invite Family') XXXX
        XXXXXX

        XXXXXXXXX
            XXXXXXX
                XXXXXXX
                    XXXX
                        XXXX gettext(u'Memorial') XXXXX
                        XXXX gettext(u'Created') XXXXX
                        XXXX gettext(u'Pending') XXXXX
                        XXXX gettext(u'Approved') XXXXX
                        XXXX gettext(u'Actions') XXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                BBB B BB BBBBB
                    XXXX
                        XXXXXXXXX
                        XXXXFFFFFFFFFFFFXXXXX
                        XXXXXXXXX
                        XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXX
                            XX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX gettext(u'Family') XXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'QR') XXXX
                            XX XXXXXXX XXXXXXXXXXXXX XXXXXXXX gettext(u'Invite') XXXX
                            XX XXXXXXX XXXXXXXXXXX XX XXXXXXX gettext(u'Edit') XXXX
                        XXXXX
                    XXXXX
                BBBBB
                    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'No memorials yet') XXXXXXXXXX
                BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXXXXXX
    XXXXXXX
XXXXXXX
XXXXXXX
