XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
        XXXX X XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX XXXXX X
        XXXXX X XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXX XXXX XX X
        XXX XX X XXXXXXX XXX XXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXX X
        XX X XXXXXXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXX X XXXXXX XXXXXX X
        XXXXXX X XXXXXX XXXX X
        XXXXXX X XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXXXXXXX XXXXX XXXXXXXXX
    
    XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFF FFFFXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFF FFFFXXXXXXXXXX
    XXXXXXXX
    
    XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
            XXXXXXXXXXXXXXXXX
            XXXX gettext(u'Memorial') XXXXX
            XXX XXXXXXXBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXXBBBBXXXXXBBBBBXX
                BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBX XXXXXXXXXXBBBBX XXX XXXXXXXXXXBBBBB
            XXXXX
        XXXXX
        XXXX
            XXXXXXXXXXXXX
            XXXX gettext(u'Save') XXXXX
            XXX XXXXXXXBB BBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBXXXXXBBBBBXX
                BB BBBBBB BB BBBBBBBBBBBBX XXXXXXXXXXBBBBX XXX XXXXXXXXXXBBBBB
            XXXXX
        XXXXX
        XXXX
            XXXXXXXXXXXXXXX
            XXXX gettext(u'Delete') XXXXX
            XXX XXXXXXXBB BBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXBBBBXXXXXBBBBBXX
                BB BBBBBBBB BB BBBBBBBBBBBBBBX XXXXXXXXXXBBBBX XXX XXXXXXXXXXBBBBB
            XXXXX
        XXXXX
        XXXX
            XXXXXXXXXXXXX
            XXXX gettext(u'Home') XXXXX
            XXX XXXXXXXBB BBBBBB BB BBBBBBBBBBBBXXXXXXXBBBBXXXXXBBBBBXX
                BB BBBBBB BB BBBBBBBBBBBBX XXXXXXXXXXBBBBX XXX XXXXXXXXXXBBBBB
            XXXXX
        XXXXX
    XXXXXXXX
    
    XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXX
    XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXX
    
    XXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
        XXXXXFFFFFFXXXXXX
    XXXXXX
    
    XXXXXXXX XXXXX XX XXXXX XXXXXXXXXXXXXX
    XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
    XXXXX
    
    XXXXXXXX
        XX XXXXXXXXX XXXXXXX XXXX X XXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXX XXX X XXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXX X XXXXXXXXXXXXXXX
                X
            X
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX