BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB BBBBBBBB X BBBBB X  _('Django site admin') BBBBBBBB

BBBBB BBBBBBBB
XXX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXX _('Django administration') XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
    XXXX XX XXXXXXXXXXX XXXXXX XXXXXXXXX XXX XXXXXXXXXXXX XXX
    BB BBBBBBBB
        XX XXXXXXXX gettext(u'View site') XXXX X
    BBBBB
    
    BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
        BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
        BB BBBBBBBB
            XX XXXXXXXX gettext(u'Documentation') XXXX X
        BBBBB
    BBBBB
    
    BB BBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Change password') XXXX X
    BBBBB
    
    XXXX XX XXXXXXXXXXXXX XXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Toggle theme') X XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX X
    
    XXXX XX XXXXXX XXXX XXXXXXXXX XXXXXX XXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
             gettext(u'Log out') 
        XXXXXXXXX
    XXXXXXX
BBBBBBBB