XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBB

XXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XX
XXXXXXX XXXXXXXXXXXXX X
    XXXXXXXX XXXXX XXXXXXXXXXX
    XXXXXXXXX XXXXXXXX XXXXXXXXXXX
    XXXXXX XXXX XXXXXXXXXXX
    XXXX XXXX XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
    XXXXXXX X XXXXXXXXXXX
X

XX XXXXXXXXXX XXXXXXXXX XXXXX XX
XXXXXXXXX X
    XXXXXXXXXXXXXX XXXX XXXXXXXXXXX
    XXXXXXXXX XXXXXXXXX
X

XX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XX
XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXXXXXXXX
X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBB

XXXXXXXX
XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX
    
    XX XX XXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
    
    XX XX XXXXX XXXXXX X XXXXXXXXXX X XXXXXXXXX
    XX XXXXXXXXXXXXXXXXXX X XX X
        XXXXX XXXXXX X XXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXX X
            XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X X
                XXXXXXXX XXXXX XXXXXXXXXXX
                XXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXXXX XXXX XXXXXXXXXXX
                XXXX XXXX XXXXXXXXXXX
                XXXXXXXX XXXX XXXXXXXXXXX
                XXXXXXX X XXXXXXXXXXX
            XX
            
            XX XXXXXXXXX X XXXXXXXXX XXXX XXX XX XXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            
            XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        X
    X XXXX X
        XX XX XXXX XXXXXX XX XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXX XXXXXX
        
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXX
        XXXXXXXXXXXXXXXXXXXX X X
            XXXXXXXXX XXXXXXXX XXXXXXXXXXX
            XXXXXX XXXX XXXXXXXXXXX
            XXXX XXXX XXXXXXXXXXX
            XXXXXXXX XXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXX XXXX
        XX
        
        XXXXXXXXXXXXXX X XXXXXXXXXX X
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
            XXXXX XXXX X XXXXXXX XXX XXXXXX X XXXXXXX X XXXXXXX XXX XXXXXXX X XXXXXX X XXXXXXX
            
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXX X XXXX XXX XXXXXX X XXXX X XXXX
        XX
        
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXX XXX XXXXXX X XXXX X XXXX
            X
        X
    X
    
    XX XX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXX
    XXXXXXXXXXXXX XX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX X XX X
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX X XXX
            XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
                XXXXXXXXXXXXXXXXXXXX
            X
        X
    XX XXXXX
XXX
XXXXXXXXX
BBBBBBBB