XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X 
            XXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX 
            XXXXXXXXXXX XXXXXXXX 
            XXXXXXXX XXXXX 
            XXXXXXXXXXX XXXXXXX 
            XXXXXXXXXX XXXXXX
            XXXXXXX X XXXXX
        X
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXXX X
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXX XXXX XX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXX
        X
        XXXXXXXX X
            XXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXX
        X
        XXXX X
            XXXXXXXX XXXX XXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
        X
        XXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
        X
        XXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
            XXXXXXX XXX XXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XX XXXXXX XXXXXXXXXXXXX 
        
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBB
                
            BBBB
                XX XXXXXXX XXXXX XXXXXXXXX
            BBBBB
        XXXXXX
        
        XXXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXXX
            XXXXXXXXX XXXX XXXXXXX XX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXXX
        XXXXX
        
        XXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XX XXXXXXXX XXXXXXXX
            XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXX
        XXXXXX
        
        XX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXX
            XX XXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXX
        XXXX
    XXXXXX
XXXXXXX
XXXXXXX