BBBB BBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX  X XXXXXX XXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    
    XXXXXXX
        XXXXX X
            XX XXXXXXXX XXXXX XX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX XX XX XXXXX
        X
        
        X X
            XXXXXXX XX
            XXXXXXXX XX
            XXXXXXXXXXX XXXXXXXXXXX
        X
        
        XXXX X
            XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XX XXXXX X XXXXX XXXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X
        
        XX XXXXXXXXX XX
        XXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXX X XXXXX
            XXXXXXXX XXXX XXXXX
        X
        
        XX XXXXXXXX XX
        XXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXX
        X
        
        XX XXXXXXXXX XX
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XX XXXX XXXXX XX
        XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXX
            XXXXXXX XXXX XX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
        X
        
        XX XXXXXXXXXXXXX XX
        XXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXX XXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXXXX XXXX XXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXX XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXXX XX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXX XXXX
            XXXX XXXXX
        X
        
        XXXXXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXX XXXX
            X
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX X XXX XXX XX
        X
        
        XXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXX
        X
        
        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XX XXXXXX XX
        XXXX X
            XXXXXXXX XXXXXXX XXXXXXX
            XXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXX XXXXXXXX
            XXXXXXXXXXX XXX XXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXX XXXXXXX
        X
        
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXX
        X
        
        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
        X
        
        XX XXXXXX XX
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXX
            XXXXXXX XXXX XX
            XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXX XXX XXXXXXXXXXX XXXXXX
        X
        
        XXXXXXXXXXX X
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        
        XX XXXXXXXXX XXXXXXXX XX
        XXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXX XXXX X XXXX XX
            XXXXXXXXX XXXXXXXXX
        X
        
        XXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXX
            XXXXXXXX XXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXX X XXXXXXX XXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
            XXXXXX
            BBBBB
            
            BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
        
        BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
    XXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXX XXXXXXXX XXX
        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXX XXXX gettext(u'New') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXX XXXX gettext(u'All Tribute') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXX XXXX gettext(u'Memories') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFXXXXXX
            XXXXXX
        XXXXXXXXXX
        XXXX XXXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBB
        XXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Life Story') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                FFFFFFFFFF
            XXXXXX
        XXXXXXXXXX
        BBBBB

        XXXX XXXXXXXXXXX XXX
        BB BBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Memories') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBB BB BBBBBB
                XX XXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXX 
                         XXXXXFFFFFFFFFFFFFFFX 
                         XXXXXXXXXXXXXXXXXX
                XXXX
                BBBB
                XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXFFFFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXX
                BBBBB
            XXXXXX
            BBBBBB
        XXXXXX
        BBBBB
        XXXX XXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX gettext(u'Add Photos or Documents') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Select file') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                    XXXXXX
            
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Type') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX gettext(u'Photo') XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Document') XXXXXXXXX
                        XXXXXXXXX
                    XXXXXX
            
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Description')  X gettext(u'optional') XXXXXXXXX
                        XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 
                                  XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
            
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Upload') XXXXXXXXX
                XXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXXXXXX
        XX XXXXXXXXXX XXX XXXXXXXXX XXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXX
    
            XXXXX XXXXXXXX X XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
            XXXXXXXXXXXXXXXXXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXXXXX XX
                XX  
                XXXXX XXXXXXXX
            XX
            XXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXX 
                X XXXX X
                    XXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXX XXXXXXXXXXXXXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X XXXXX X XXXXXXXXX
            XXX
        XXX
        XXXXXXXXX       
        
        XXXX XXXXXXX XXX
        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Filters') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Date') XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXX gettext(u'All') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX gettext(u'Today') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX gettext(u'Last 7 days') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX gettext(u'Last 30 days') XXXXXXXXX
                    XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Author') XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search by author...') XXX
                XXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Apply') XXXXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Reset') XXXXXXXXX
            XXXXXX
        XXXXXXXXXX

        XXXX XXXXXXXXX XXXXXXXX XXX
        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Condolences') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                     gettext(u'Pending Review')  XFFFFFFX
                XXXXX
                
                BBB BBBBBBB BB BBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXFFFFFX XXXXXXXXXXXFFFFFFFFFFFFXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Author') X XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Text') X XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Date') X FFFFFFFFFFF FFFFXXXXXX
                    
                    XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXX
                        XXXXX XXXXXXXXXXXXX 
                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                              XXXXXXXXXXXX XXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                                X  gettext(u'Approve') 
                            XXXXXXXXX
                        XXXXXXX

                        XXXXX XXXXXXXXXXXXX 
                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                              XXXXXXXXXXXX XXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                                X  gettext(u'Reject') 
                            XXXXXXXXX
                        XXXXXXX
                    XXXXXX
                XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'No condolences awaiting moderation') 
                XXXXXX
                BBBBBB
            XXXXXX

            XXXX XXXXXXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                     gettext(u'Approved')  XFFFFFFX
                XXXXX
                
                BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFX XXXXXXXXXXXFFFFFFFFFFFFXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFF FFFFXXXXXX
                XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'No approved condolences yet') 
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
    XXXXXXX

    XXXXXXXX
        XX XXXXXXX XX XXXX X XXXXXX
        XXXXXXXX XXXXXXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX X XXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
                XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXX X XXXXX
                XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXX X XXXXXX
                X
                XX XXXXXXXX XXX XXXXX XX XXXXXXXX X
                    XXXXX X X XXX XXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXX XXXXXXXX X XXXXXX X XX X XXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXX XXXXXXX XX XXXXXXXX X XX XXXX X XXXXXX
                    XX XXXXXXXX XXX XXXXXX XX XXXXXXXX X XX XXXX X XXXXXX
                    XX XXXXXXXX XXX XXXXXXX XX XXXXXXXX X XXX XXXX X XXXXXX
                X
                XXXXXXXXXXXXXXXXXX X XXXX X XX X XXXXXXX
            XXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
            XXXXXXXXXXXXXXX
        XXX
        XX XXXXXXXXXXX X XXXXX XXXXXXXXX X XXXXXXXXXXXXXX XXXXXX XX XXXXXX
        XX XXXXXXXXXXXXX XXXXXXXX XX XXXXXXX X XXXX XXXXXXX XXXXX XXXXXXXX X XXXXX
        XXX XXXXXXXXXXXXXXXX X XXXXXXXXFFFFFFXX XX XX
        XXXXXXXX XXXXXXXXXX X
            XXX X
                XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX X X XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX X X XXXXXXXXXXXXXXXXX
                XXXXXX X XXXXXXX XXXXXXXXXXXXXXXXX X XXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXX
                XXXXXXXXXX
                XXXXXXXXXXXXX XX X XXXXXXXXX XXXXXXXXXXXX XX XXXXX
            X XXXXXXXX XX
        X
        XXXXXXXX XXXXXXXXXXXXXX X
            XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXX X XXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXX X XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXX
        X
        XXXXXXXX XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXXXXXXXXXXXXXXX XXX
            XX
            XXXXXXX XX XXXXXXXXX
            XXXXXXXXXX XX X
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X XX
                XX XXXXXX X XXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                X
                XXXXXXXXXXXXXXXX X XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XX
            XXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        
        XX XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXX XXX XXXXXXX X
                XXXXX XXXX X XXXXXXXXX
                XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX X XXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                X
            X
        XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
