XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX X  XXXXXXXX
    XXXXXXX
        XXXXXXXX X XXXXXXX XXX XXXXX XXXXX XXXXXXXX XXXXX XXXXXXX XXXX XX XXXXXXXXXXXXXX XXXX X
        XXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXX X XXXXXXXXXXX XXXXX X
        XXXXXX X XXXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXX XXXXXXX XXXXXXXX X
        XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXX X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXXXXX XXXXXXX XXXXXXXXXX X  XXXXX
    
    XXXXXXXXXXX XXXXXXXX XFFFFFFXXXXXX
    BBB BBBBBBB BB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFF FFFFXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
                BBBBBBBBBB
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
    BBBBB
    XXXXX XXXXXXX XXXXXXXX XX XXXXXXXXXXXXX 
    BBBBBB
    
    XXXXXXXXXXXX XXXXXXXX XFFFFFFXXXXXX
    BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFF FFFFXXXX
        XXXFFFFFFFFFFXXXX
    XXXXXX
    BBBBB
    XXXXX XXXXXXXX XXXXXXXX XXXXXXXX
    BBBBBB
XXXXXXX
XXXXXXX