BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX XX XX XXXXX
        X
        X X XXXXXXX XX XXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXX X
        XXXX X
            XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXX
            XXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXX
        X
        XXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXX X XXXXX XXXXXXXX XXXX XXXXX X
        XXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXX X
        XXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX X
        XXXX X XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXX XX X
        XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBXXXXXFFFFFFFFFFFFXXXXXXBBBBB
            BB BBBBBBBBBBBBBBBBBBBXXXXXFFFFFFFFFFFFXXXXXXBBBBB
        XXXXXX
        BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB
    XXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBB
        XXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Life Story') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXX
        XXXXXXXXXX
        BBBBB

        BB BBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Memories') XXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBB BB BBBBBB
                XX XXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXX XXXXXFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXX
                XXXX
                BBBB
                XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXFFFFFFFFFFFFFFFFFFXXXXXX
                    XXXXXX
                XXXX
                BBBBB
            XXXXXX
            BBBBBB
        XXXXXX
        BBBBB

        XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Leave a Tribute') XXXXX
            XXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Your name')  XXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX gettext(u'Message')  XXXXXXXXX
                    XXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Send Tribute') XXXXXXXXX
            XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX gettext(u'Recent Tributes') XXXXX
            BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Author') X XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Message') X XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Date') X FFFFFFFFFFF FFFFXXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'No tributes yet') XXXXXX
            BBBBBB
        XXXXXXXXXX
    XXXXXXX

    XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX X
        XXX XXXXXXXXXXX X XXXXX
        XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                    XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                    XXXXXX
                X
            X
        X
        XXXXXX XXXXXXXXXXXX
    X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
        XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXX X XXX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X
                XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXX XX XX
            XX
            XXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        XXXXXXXXXXXXX XXXXXX XX X
            XX XXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXX XXXX XXXX XXXXXXX XXX XXXX XXXX XXX XXXXXXXXX
            X XXXX X
                XXXXX X X XXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXX X X XX
            X
        XXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXX X X XXXX
        XXX
    XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
