XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XX XXXX XXXXXXXXXXXX
    XXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXX
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXX XXXXX XXXXXX XXXXXX XXX XXX XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XX X
                    XX XXXXXXXXX XXXXXXXXXX XXX
                    XXXXXXXXXXXXX
                    
                    XX XXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X 
                            XXX XXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
                    X
                XX
                XXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X 
                        XXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                XXX
        X
        
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXX X
                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXX XXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXX X
                        XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                    X XXXX XX XXXXXXXXXXXX XXX XXXXX X
                        XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                    X XXXX X
                        XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
                    X
                XXX
                
                XXXX XX XXXXXXXX
                XXXX XX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXXXXX XXX XXXXX
                XXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                    XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXX
                XXXX XX XXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXXXXXXX X XXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXX XXX XXXXXXXXXXXXXX
            X
        X
        
        XX XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXX XXXXXXXX
        XXXXXXXXXXXXX X XXXXXXXXXX X
            XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXXX
            XXXXXXXXXXXXXXXXXXXXXXX
        XX
    XXXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX
    
    XXXXXXXX XX XXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXX XXX
    XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX
    
        XX XXXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX X
                XX XXXXXXXXXXXXXX X
                    XXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                X
                XXXXXX XXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXXXX XX X
                XX XXXXXXX XXXXXXXXXX XXXXXXXX
                XX XXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXX X XXXXXXXXXX
                X
            
                XX XXXXXXXXX XXX
                XXX X
                    XXXXXXXXXXXXX
                
                    XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X
                        XXXXX XXXXXXX X XXXXXXXXXXXXXXX
                        XXX XXXX X XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    
                        XX XXXXXXXXX XXXXXXXX XXXXX
                        XXXXX XXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX
                        XXXX XX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX XX X
                            XX XXXXXXXXXXXXXXX X
                                XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
                            X XXXX X
                                XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
                            X
                        XXX 
                        XXXX XX XXXXXXXX
                    
                        XXXXXXXXXXXXXXXXX X XXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
                    X
                X XXXXX XXXXXXX X
                    XXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
                X
            XX
            XXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
            XXX
X
XXXXXXXXX
    
    XXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXX XXXX XXXXXXXXXXX
    XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXX
    XXXXX
    
    XXXXXXXX XX XXXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXX XXXXX XXX XXXXXXXX
    XXXXX
XX XXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

XX XX XX XXXXX XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXX
XXXXXXX